# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
    os: Ubuntu-22.04

python:
    version: "3.11"
    install:
        # 1) install the docs dependencies
        -   requirements: docs/requirements.txt
        # 2) install your package itself (so autodoc can import it)
        -   method: pip
            path: .

sphinx:
    configuration: docs/source/conf.py
    # optional, but makes warnings fail the build:
    # fail_on_warning: true

formats:
  - htmlzip
  - pdf
  - epub

